//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Snoffleware.LLBLGen.Identity.Core.Data.HelperClasses;
using Snoffleware.LLBLGen.Identity.Core.Data.FactoryClasses;
using Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Snoffleware.LLBLGen.Identity.Core.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AspNetUserRole'.<br/><br/></summary>
	[Serializable]
	public partial class AspNetUserRoleEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AspNetRoleEntity _aspNetRole;
		private AspNetUserEntity _aspNetUser;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AspNetUserRoleEntityStaticMetaData _staticMetaData = new AspNetUserRoleEntityStaticMetaData();
		private static AspNetUserRoleRelations _relationsFactory = new AspNetUserRoleRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AspNetRole</summary>
			public static readonly string AspNetRole = "AspNetRole";
			/// <summary>Member name AspNetUser</summary>
			public static readonly string AspNetUser = "AspNetUser";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AspNetUserRoleEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AspNetUserRoleEntityStaticMetaData()
			{
				SetEntityCoreInfo("AspNetUserRoleEntity", InheritanceHierarchyType.None, false, (int)Snoffleware.LLBLGen.Identity.Core.Data.EntityType.AspNetUserRoleEntity, typeof(AspNetUserRoleEntity), typeof(AspNetUserRoleEntityFactory), false);
				AddNavigatorMetaData<AspNetUserRoleEntity, AspNetRoleEntity>("AspNetRole", "AspNetUserRoles", (a, b) => a._aspNetRole = b, a => a._aspNetRole, (a, b) => a.AspNetRole = b, Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses.StaticAspNetUserRoleRelations.AspNetRoleEntityUsingRoleIdStatic, ()=>new AspNetUserRoleRelations().AspNetRoleEntityUsingRoleId, null, new int[] { (int)AspNetUserRoleFieldIndex.RoleId }, null, true, (int)Snoffleware.LLBLGen.Identity.Core.Data.EntityType.AspNetRoleEntity);
				AddNavigatorMetaData<AspNetUserRoleEntity, AspNetUserEntity>("AspNetUser", "AspNetUserRoles", (a, b) => a._aspNetUser = b, a => a._aspNetUser, (a, b) => a.AspNetUser = b, Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses.StaticAspNetUserRoleRelations.AspNetUserEntityUsingUserIdStatic, ()=>new AspNetUserRoleRelations().AspNetUserEntityUsingUserId, null, new int[] { (int)AspNetUserRoleFieldIndex.UserId }, null, true, (int)Snoffleware.LLBLGen.Identity.Core.Data.EntityType.AspNetUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AspNetUserRoleEntity()
		{
		}

		/// <summary> CTor</summary>
		public AspNetUserRoleEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AspNetUserRoleEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AspNetUserRoleEntity</param>
		public AspNetUserRoleEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="roleId">PK value for AspNetUserRole which data should be fetched into this AspNetUserRole object</param>
		/// <param name="userId">PK value for AspNetUserRole which data should be fetched into this AspNetUserRole object</param>
		public AspNetUserRoleEntity(System.String roleId, System.String userId) : this(roleId, userId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="roleId">PK value for AspNetUserRole which data should be fetched into this AspNetUserRole object</param>
		/// <param name="userId">PK value for AspNetUserRole which data should be fetched into this AspNetUserRole object</param>
		/// <param name="validator">The custom validator object for this AspNetUserRoleEntity</param>
		public AspNetUserRoleEntity(System.String roleId, System.String userId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.RoleId = roleId;
			this.UserId = userId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AspNetUserRoleEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AspNetRole' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAspNetRole() { return CreateRelationInfoForNavigator("AspNetRole"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AspNetUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAspNetUser() { return CreateRelationInfoForNavigator("AspNetUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AspNetUserRoleEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AspNetUserRoleRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AspNetRole' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAspNetRole { get { return _staticMetaData.GetPrefetchPathElement("AspNetRole", CommonEntityBase.CreateEntityCollection<AspNetRoleEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AspNetUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAspNetUser { get { return _staticMetaData.GetPrefetchPathElement("AspNetUser", CommonEntityBase.CreateEntityCollection<AspNetUserEntity>()); } }

		/// <summary>The RoleId property of the Entity AspNetUserRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AspNetUserRoles"."RoleId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 450.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String RoleId
		{
			get { return (System.String)GetValue((int)AspNetUserRoleFieldIndex.RoleId, true); }
			set	{ SetValue((int)AspNetUserRoleFieldIndex.RoleId, value); }
		}

		/// <summary>The UserId property of the Entity AspNetUserRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AspNetUserRoles"."UserId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 450.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String UserId
		{
			get { return (System.String)GetValue((int)AspNetUserRoleFieldIndex.UserId, true); }
			set	{ SetValue((int)AspNetUserRoleFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AspNetRoleEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AspNetRoleEntity AspNetRole
		{
			get { return _aspNetRole; }
			set { SetSingleRelatedEntityNavigator(value, "AspNetRole"); }
		}

		/// <summary>Gets / sets related entity of type 'AspNetUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AspNetUserEntity AspNetUser
		{
			get { return _aspNetUser; }
			set { SetSingleRelatedEntityNavigator(value, "AspNetUser"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Snoffleware.LLBLGen.Identity.Core.Data
{
	public enum AspNetUserRoleFieldIndex
	{
		///<summary>RoleId. </summary>
		RoleId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AspNetUserRole. </summary>
	public partial class AspNetUserRoleRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AspNetUserRoleEntity and AspNetRoleEntity over the m:1 relation they have, using the relation between the fields: AspNetUserRole.RoleId - AspNetRole.Id</summary>
		public virtual IEntityRelation AspNetRoleEntityUsingRoleId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AspNetRole", false, new[] { AspNetRoleFields.Id, AspNetUserRoleFields.RoleId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AspNetUserRoleEntity and AspNetUserEntity over the m:1 relation they have, using the relation between the fields: AspNetUserRole.UserId - AspNetUser.Id</summary>
		public virtual IEntityRelation AspNetUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AspNetUser", false, new[] { AspNetUserFields.Id, AspNetUserRoleFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAspNetUserRoleRelations
	{
		internal static readonly IEntityRelation AspNetRoleEntityUsingRoleIdStatic = new AspNetUserRoleRelations().AspNetRoleEntityUsingRoleId;
		internal static readonly IEntityRelation AspNetUserEntityUsingUserIdStatic = new AspNetUserRoleRelations().AspNetUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticAspNetUserRoleRelations() { }
	}
}
