//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Snoffleware.LLBLGen.Identity.Core.Data.HelperClasses;
using Snoffleware.LLBLGen.Identity.Core.Data.FactoryClasses;
using Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Snoffleware.LLBLGen.Identity.Core.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AspNetUserClaim'.<br/><br/></summary>
	[Serializable]
	public partial class AspNetUserClaimEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AspNetUserEntity _aspNetUser;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AspNetUserClaimEntityStaticMetaData _staticMetaData = new AspNetUserClaimEntityStaticMetaData();
		private static AspNetUserClaimRelations _relationsFactory = new AspNetUserClaimRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AspNetUser</summary>
			public static readonly string AspNetUser = "AspNetUser";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AspNetUserClaimEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AspNetUserClaimEntityStaticMetaData()
			{
				SetEntityCoreInfo("AspNetUserClaimEntity", InheritanceHierarchyType.None, false, (int)Snoffleware.LLBLGen.Identity.Core.Data.EntityType.AspNetUserClaimEntity, typeof(AspNetUserClaimEntity), typeof(AspNetUserClaimEntityFactory), false);
				AddNavigatorMetaData<AspNetUserClaimEntity, AspNetUserEntity>("AspNetUser", "AspNetUserClaims", (a, b) => a._aspNetUser = b, a => a._aspNetUser, (a, b) => a.AspNetUser = b, Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses.StaticAspNetUserClaimRelations.AspNetUserEntityUsingUserIdStatic, ()=>new AspNetUserClaimRelations().AspNetUserEntityUsingUserId, null, new int[] { (int)AspNetUserClaimFieldIndex.UserId }, null, true, (int)Snoffleware.LLBLGen.Identity.Core.Data.EntityType.AspNetUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AspNetUserClaimEntity()
		{
		}

		/// <summary> CTor</summary>
		public AspNetUserClaimEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AspNetUserClaimEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AspNetUserClaimEntity</param>
		public AspNetUserClaimEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AspNetUserClaim which data should be fetched into this AspNetUserClaim object</param>
		public AspNetUserClaimEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AspNetUserClaim which data should be fetched into this AspNetUserClaim object</param>
		/// <param name="validator">The custom validator object for this AspNetUserClaimEntity</param>
		public AspNetUserClaimEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AspNetUserClaimEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AspNetUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAspNetUser() { return CreateRelationInfoForNavigator("AspNetUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AspNetUserClaimEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AspNetUserClaimRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AspNetUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAspNetUser { get { return _staticMetaData.GetPrefetchPathElement("AspNetUser", CommonEntityBase.CreateEntityCollection<AspNetUserEntity>()); } }

		/// <summary>The ClaimType property of the Entity AspNetUserClaim<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AspNetUserClaims"."ClaimType".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ClaimType
		{
			get { return (System.String)GetValue((int)AspNetUserClaimFieldIndex.ClaimType, true); }
			set	{ SetValue((int)AspNetUserClaimFieldIndex.ClaimType, value); }
		}

		/// <summary>The ClaimValue property of the Entity AspNetUserClaim<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AspNetUserClaims"."ClaimValue".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ClaimValue
		{
			get { return (System.String)GetValue((int)AspNetUserClaimFieldIndex.ClaimValue, true); }
			set	{ SetValue((int)AspNetUserClaimFieldIndex.ClaimValue, value); }
		}

		/// <summary>The Id property of the Entity AspNetUserClaim<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AspNetUserClaims"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)AspNetUserClaimFieldIndex.Id, true); }
			set { SetValue((int)AspNetUserClaimFieldIndex.Id, value); }		}

		/// <summary>The UserId property of the Entity AspNetUserClaim<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AspNetUserClaims"."UserId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 450.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String UserId
		{
			get { return (System.String)GetValue((int)AspNetUserClaimFieldIndex.UserId, true); }
			set	{ SetValue((int)AspNetUserClaimFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AspNetUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AspNetUserEntity AspNetUser
		{
			get { return _aspNetUser; }
			set { SetSingleRelatedEntityNavigator(value, "AspNetUser"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Snoffleware.LLBLGen.Identity.Core.Data
{
	public enum AspNetUserClaimFieldIndex
	{
		///<summary>ClaimType. </summary>
		ClaimType,
		///<summary>ClaimValue. </summary>
		ClaimValue,
		///<summary>Id. </summary>
		Id,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Snoffleware.LLBLGen.Identity.Core.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AspNetUserClaim. </summary>
	public partial class AspNetUserClaimRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AspNetUserClaimEntity and AspNetUserEntity over the m:1 relation they have, using the relation between the fields: AspNetUserClaim.UserId - AspNetUser.Id</summary>
		public virtual IEntityRelation AspNetUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AspNetUser", false, new[] { AspNetUserFields.Id, AspNetUserClaimFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAspNetUserClaimRelations
	{
		internal static readonly IEntityRelation AspNetUserEntityUsingUserIdStatic = new AspNetUserClaimRelations().AspNetUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticAspNetUserClaimRelations() { }
	}
}
