//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Snoffleware.LLBLGen.Identity.Core.Data.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitAspNetRoleEntityMappings();
			InitAspNetRoleClaimEntityMappings();
			InitAspNetUserEntityMappings();
			InitAspNetUserClaimEntityMappings();
			InitAspNetUserLoginEntityMappings();
			InitAspNetUserRoleEntityMappings();
			InitAspNetUserTokenEntityMappings();
		}

		/// <summary>Inits AspNetRoleEntity's mappings</summary>
		private void InitAspNetRoleEntityMappings()
		{
			this.AddElementMapping("AspNetRoleEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetRoles", 4, 0);
			this.AddElementFieldMapping("AspNetRoleEntity", "ConcurrencyStamp", "ConcurrencyStamp", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetRoleEntity", "Id", "Id", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetRoleEntity", "Name", "Name", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetRoleEntity", "NormalizedName", "NormalizedName", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetRoleClaimEntity's mappings</summary>
		private void InitAspNetRoleClaimEntityMappings()
		{
			this.AddElementMapping("AspNetRoleClaimEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetRoleClaims", 4, 0);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "ClaimType", "ClaimType", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "ClaimValue", "ClaimValue", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "RoleId", "RoleId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetUserEntity's mappings</summary>
		private void InitAspNetUserEntityMappings()
		{
			this.AddElementMapping("AspNetUserEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetUsers", 15, 0);
			this.AddElementFieldMapping("AspNetUserEntity", "AccessFailedCount", "AccessFailedCount", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("AspNetUserEntity", "ConcurrencyStamp", "ConcurrencyStamp", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserEntity", "Email", "Email", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetUserEntity", "EmailConfirmed", "EmailConfirmed", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 3);
			this.AddElementFieldMapping("AspNetUserEntity", "Id", "Id", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("AspNetUserEntity", "LockoutEnabled", "LockoutEnabled", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("AspNetUserEntity", "LockoutEnd", "LockoutEnd", true, "DateTimeOffset", 0, 0, 0, false, "", null, typeof(System.DateTimeOffset), 6);
			this.AddElementFieldMapping("AspNetUserEntity", "NormalizedEmail", "NormalizedEmail", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("AspNetUserEntity", "NormalizedUserName", "NormalizedUserName", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("AspNetUserEntity", "PasswordHash", "PasswordHash", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("AspNetUserEntity", "PhoneNumber", "PhoneNumber", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("AspNetUserEntity", "PhoneNumberConfirmed", "PhoneNumberConfirmed", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 11);
			this.AddElementFieldMapping("AspNetUserEntity", "SecurityStamp", "SecurityStamp", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("AspNetUserEntity", "TwoFactorEnabled", "TwoFactorEnabled", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 13);
			this.AddElementFieldMapping("AspNetUserEntity", "UserName", "UserName", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 14);
		}

		/// <summary>Inits AspNetUserClaimEntity's mappings</summary>
		private void InitAspNetUserClaimEntityMappings()
		{
			this.AddElementMapping("AspNetUserClaimEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetUserClaims", 4, 0);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "ClaimType", "ClaimType", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "ClaimValue", "ClaimValue", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetUserLoginEntity's mappings</summary>
		private void InitAspNetUserLoginEntityMappings()
		{
			this.AddElementMapping("AspNetUserLoginEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetUserLogins", 4, 0);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "LoginProvider", "LoginProvider", false, "NVarChar", 128, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "ProviderDisplayName", "ProviderDisplayName", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "ProviderKey", "ProviderKey", false, "NVarChar", 128, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetUserRoleEntity's mappings</summary>
		private void InitAspNetUserRoleEntityMappings()
		{
			this.AddElementMapping("AspNetUserRoleEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetUserRoles", 2, 0);
			this.AddElementFieldMapping("AspNetUserRoleEntity", "RoleId", "RoleId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserRoleEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits AspNetUserTokenEntity's mappings</summary>
		private void InitAspNetUserTokenEntityMappings()
		{
			this.AddElementMapping("AspNetUserTokenEntity", @"Snoffleware-LLBLGen-Identity-Dev", @"dbo", "AspNetUserTokens", 4, 0);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "LoginProvider", "LoginProvider", false, "NVarChar", 128, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "Name", "Name", false, "NVarChar", 128, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "Value", "Value", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
		}

	}
}
