//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Snoffleware.LLBLGen.Identity.Core.Data.HelperClasses
{
	/// <summary>Field Creation Class for entity AspNetRoleEntity</summary>
	public partial class AspNetRoleFields
	{
		/// <summary>Creates a new AspNetRoleEntity.ConcurrencyStamp field instance</summary>
		public static EntityField2 ConcurrencyStamp { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleFieldIndex.ConcurrencyStamp); }}
		/// <summary>Creates a new AspNetRoleEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleFieldIndex.Id); }}
		/// <summary>Creates a new AspNetRoleEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleFieldIndex.Name); }}
		/// <summary>Creates a new AspNetRoleEntity.NormalizedName field instance</summary>
		public static EntityField2 NormalizedName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleFieldIndex.NormalizedName); }}
	}

	/// <summary>Field Creation Class for entity AspNetRoleClaimEntity</summary>
	public partial class AspNetRoleClaimFields
	{
		/// <summary>Creates a new AspNetRoleClaimEntity.ClaimType field instance</summary>
		public static EntityField2 ClaimType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleClaimFieldIndex.ClaimType); }}
		/// <summary>Creates a new AspNetRoleClaimEntity.ClaimValue field instance</summary>
		public static EntityField2 ClaimValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleClaimFieldIndex.ClaimValue); }}
		/// <summary>Creates a new AspNetRoleClaimEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleClaimFieldIndex.Id); }}
		/// <summary>Creates a new AspNetRoleClaimEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetRoleClaimFieldIndex.RoleId); }}
	}

	/// <summary>Field Creation Class for entity AspNetUserEntity</summary>
	public partial class AspNetUserFields
	{
		/// <summary>Creates a new AspNetUserEntity.AccessFailedCount field instance</summary>
		public static EntityField2 AccessFailedCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.AccessFailedCount); }}
		/// <summary>Creates a new AspNetUserEntity.ConcurrencyStamp field instance</summary>
		public static EntityField2 ConcurrencyStamp { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.ConcurrencyStamp); }}
		/// <summary>Creates a new AspNetUserEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.Email); }}
		/// <summary>Creates a new AspNetUserEntity.EmailConfirmed field instance</summary>
		public static EntityField2 EmailConfirmed { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.EmailConfirmed); }}
		/// <summary>Creates a new AspNetUserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.Id); }}
		/// <summary>Creates a new AspNetUserEntity.LockoutEnabled field instance</summary>
		public static EntityField2 LockoutEnabled { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.LockoutEnabled); }}
		/// <summary>Creates a new AspNetUserEntity.LockoutEnd field instance</summary>
		public static EntityField2 LockoutEnd { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.LockoutEnd); }}
		/// <summary>Creates a new AspNetUserEntity.NormalizedEmail field instance</summary>
		public static EntityField2 NormalizedEmail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.NormalizedEmail); }}
		/// <summary>Creates a new AspNetUserEntity.NormalizedUserName field instance</summary>
		public static EntityField2 NormalizedUserName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.NormalizedUserName); }}
		/// <summary>Creates a new AspNetUserEntity.PasswordHash field instance</summary>
		public static EntityField2 PasswordHash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.PasswordHash); }}
		/// <summary>Creates a new AspNetUserEntity.PhoneNumber field instance</summary>
		public static EntityField2 PhoneNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.PhoneNumber); }}
		/// <summary>Creates a new AspNetUserEntity.PhoneNumberConfirmed field instance</summary>
		public static EntityField2 PhoneNumberConfirmed { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.PhoneNumberConfirmed); }}
		/// <summary>Creates a new AspNetUserEntity.SecurityStamp field instance</summary>
		public static EntityField2 SecurityStamp { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.SecurityStamp); }}
		/// <summary>Creates a new AspNetUserEntity.TwoFactorEnabled field instance</summary>
		public static EntityField2 TwoFactorEnabled { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.TwoFactorEnabled); }}
		/// <summary>Creates a new AspNetUserEntity.UserName field instance</summary>
		public static EntityField2 UserName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserFieldIndex.UserName); }}
	}

	/// <summary>Field Creation Class for entity AspNetUserClaimEntity</summary>
	public partial class AspNetUserClaimFields
	{
		/// <summary>Creates a new AspNetUserClaimEntity.ClaimType field instance</summary>
		public static EntityField2 ClaimType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserClaimFieldIndex.ClaimType); }}
		/// <summary>Creates a new AspNetUserClaimEntity.ClaimValue field instance</summary>
		public static EntityField2 ClaimValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserClaimFieldIndex.ClaimValue); }}
		/// <summary>Creates a new AspNetUserClaimEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserClaimFieldIndex.Id); }}
		/// <summary>Creates a new AspNetUserClaimEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserClaimFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity AspNetUserLoginEntity</summary>
	public partial class AspNetUserLoginFields
	{
		/// <summary>Creates a new AspNetUserLoginEntity.LoginProvider field instance</summary>
		public static EntityField2 LoginProvider { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserLoginFieldIndex.LoginProvider); }}
		/// <summary>Creates a new AspNetUserLoginEntity.ProviderDisplayName field instance</summary>
		public static EntityField2 ProviderDisplayName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserLoginFieldIndex.ProviderDisplayName); }}
		/// <summary>Creates a new AspNetUserLoginEntity.ProviderKey field instance</summary>
		public static EntityField2 ProviderKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserLoginFieldIndex.ProviderKey); }}
		/// <summary>Creates a new AspNetUserLoginEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserLoginFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity AspNetUserRoleEntity</summary>
	public partial class AspNetUserRoleFields
	{
		/// <summary>Creates a new AspNetUserRoleEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserRoleFieldIndex.RoleId); }}
		/// <summary>Creates a new AspNetUserRoleEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserRoleFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity AspNetUserTokenEntity</summary>
	public partial class AspNetUserTokenFields
	{
		/// <summary>Creates a new AspNetUserTokenEntity.LoginProvider field instance</summary>
		public static EntityField2 LoginProvider { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserTokenFieldIndex.LoginProvider); }}
		/// <summary>Creates a new AspNetUserTokenEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserTokenFieldIndex.Name); }}
		/// <summary>Creates a new AspNetUserTokenEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserTokenFieldIndex.UserId); }}
		/// <summary>Creates a new AspNetUserTokenEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AspNetUserTokenFieldIndex.Value); }}
	}
	

}