//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using Snoffleware.LLBLGen.Identity.Core.Data.EntityClasses;
using Snoffleware.LLBLGen.Identity.Core.Data.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace Snoffleware.LLBLGen.Identity.Core.Data.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the AspNetRole entity</summary>
		public EntityQuery<AspNetRoleEntity> AspNetRole { get { return Create<AspNetRoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AspNetRoleClaim entity</summary>
		public EntityQuery<AspNetRoleClaimEntity> AspNetRoleClaim { get { return Create<AspNetRoleClaimEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AspNetUser entity</summary>
		public EntityQuery<AspNetUserEntity> AspNetUser { get { return Create<AspNetUserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AspNetUserClaim entity</summary>
		public EntityQuery<AspNetUserClaimEntity> AspNetUserClaim { get { return Create<AspNetUserClaimEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AspNetUserLogin entity</summary>
		public EntityQuery<AspNetUserLoginEntity> AspNetUserLogin { get { return Create<AspNetUserLoginEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AspNetUserRole entity</summary>
		public EntityQuery<AspNetUserRoleEntity> AspNetUserRole { get { return Create<AspNetUserRoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AspNetUserToken entity</summary>
		public EntityQuery<AspNetUserTokenEntity> AspNetUserToken { get { return Create<AspNetUserTokenEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}