//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Snoffleware.LLBLGen.Identity.Core.Data
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>AspNetRole</summary>
		AspNetRoleEntity,
		///<summary>AspNetRoleClaim</summary>
		AspNetRoleClaimEntity,
		///<summary>AspNetUser</summary>
		AspNetUserEntity,
		///<summary>AspNetUserClaim</summary>
		AspNetUserClaimEntity,
		///<summary>AspNetUserLogin</summary>
		AspNetUserLoginEntity,
		///<summary>AspNetUserRole</summary>
		AspNetUserRoleEntity,
		///<summary>AspNetUserToken</summary>
		AspNetUserTokenEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

